### ISSUE TITLE
Can we get the process pid, or a way to interact with processes?

### ISSUE THREAD

**Issue by eko234** [eburghar/kakpipe#1]
Hi, I just found your plugin and think it is pretty cool, its perfect for my workflow so thanks for your work!

my question is if there is a way kakpipe could provide the user with the PID of the process or a way to interact with the process that is spawned? maybe interacting is beyond kakpipe, I don't know, still think it'd be awesome, but about the PID, maybe you could declare a public option that is a str-to-str-map with the fifo buffer name mapping to the PID.

**Comment by eburghar** [comment]
Hi eko234,

Thank you for your interest.

The only way to interact with the process is through `:bd` to close and stop the processes and `:!!` to stop and relaunch.

kakpipe sends the pids (kakpipe and launched process) to kakoune to be sure to stop everything on close buffer. They are written on /tmp/kakpipe/.pid1 and .pid2.

The map is possible but it is certainly tricky to synchronize with processes stopping and dying... Perhaps an option to suffix the buffer name with pid so you can parse the buffer names still opened and do whatever you want with the pid ?

What is your workflow  ?

Don't hesitate to star the plugin. It's not for the fame but because kakoune plugins are referenced by github stars in kakoune site.

**Comment by eburghar** [comment]
See my message #2. Perhaps it resolves your use case

**Comment by eko234** [comment]
Hi thanks for your answer, I think I will be able to do what I need with the last change you commited, I'm firing some processes to which I want to send input, currenty my workflow is that I run some programs like servers with kakpipe so navigating the logs/errors/data has become as easy as using kakoune and that is really amazing.

Another thing that interests me a lot, is the different ways in which people have tried to implement some buffer/repl system for kakoune, I think fifos may be a good way to go about it, but on the other hand not all repl like programs behave the same in terms of the way they receive input, so I think there should be a different layer of communication for that, I say this because I think the scope in which kakpipe operates, imho, should stay as it is, and people could develop something like "fifo input adapters", to use along tools like kakpie, what do you think about it?

**Comment by eburghar** [comment]
yes, i think you are right the scope is just launching quickly some tools that have colored output and that need few interactions but it's up to you to make it broader.

You can certainly define kakoune commands to send data to the process running inside the fifo by any means (fifo, socket, ...), Create the interface upfront before launching kakpipe and give the right parameters to the process, then define others command to interact with the interface. Then evaluate if it's better inside kakoune or inside a regular shell.
