### ISSUE TITLE
Handle command composition

### ISSUE THREAD

**Issue by eko234** [eburghar/kakpipe#2]
right now I've tested a use case I wish was easier to accomplish with kakpipe, I'm runngin:

``` kakoune
:kakpipe -S -- echo hemlo fren > some_file
```
but kakpipe treats every word beyond  `--` as a literal argument, the documentation says so indeed, as `cmd` is a single positional argument and its args are variadic, and the easisest workaround is to write a bash script (or a program), that defines the behavior and let kakpipe forwared the arguments to it and do its magic.

I wonder if this could lead to some corner cases, maybe it wont, I don't know, I wanted to know what you think about it, and what do you think about the idea of the body beyond `--` being treated as a normal shell command instead of a program and its args.

**Comment by eburghar** [comment]
Hi eko234,

I managed to run your example above with

```
:kakpipe -S -n test -- sh -c 'echo hello >/tmp/foo'
```

The reason for the -n test is that I found a bug because I don't do proper escaping for creating the buffer name.

Just saw that you already had starred the plugin before I asked. Thanks for that and forget my previous message.

**Comment by eburghar** [comment]
I just pushed 0.5.7 that resolve the escaping bug.
The buffer name generation is simpler :

- either it is `*prefix-id*`. prefix is the command name of the prefix given with `-N`,
- or `*name*` when used with `-n`

Instead of the timestamp i reuse the temporary id used for generating the files in `/tmp/kakpipe`, so you can parse the buffer name to retrieve the `id` and from there, read the id in `/tmp/kakpipe/id.pid1` and `/tmp/kakpipe/id.pid2`.

If you want to launch on-the-fly script, you can do as suggested above :
```
:kakpipe -S -N alive -- sh -c 'while true; do echo alive; sleep 1; done'
```
